### ISSUE TITLE
Error when using with Vite + Vue3: Could not resolve "./Chart"

### ISSUE THREAD

**Issue by quiquelhappy** [carterbourette/vue-frappe-chart#3]
```
X [ERROR] Could not resolve "./Chart"

    node_modules/vue-frappe-chart/src/components/index.js:1:33:
      1 │ export { default as Chart } from "./Chart"
        ╵                                  ~~~~~~~~~

11:51:16 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/vue-frappe-chart/src/components/index.js:1:33: ERROR: Could not resolve "./Chart"
    at failureErrorWithLog (C:\Users\happy\Documents\GitHub\purecore\landing\node_modules\esbuild\lib\main.js:1605:15)
    at C:\Users\happy\Documents\GitHub\purecore\landing\node_modules\esbuild\lib\main.js:1251:28
    at runOnEndCallbacks (C:\Users\happy\Documents\GitHub\purecore\landing\node_modules\esbuild\lib\main.js:1034:63)
    at buildResponseToResult (C:\Users\happy\Documents\GitHub\purecore\landing\node_modules\esbuild\lib\main.js:1249:7)
    at C:\Users\happy\Documents\GitHub\purecore\landing\node_modules\esbuild\lib\main.js:1358:14
    at C:\Users\happy\Documents\GitHub\purecore\landing\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (C:\Users\happy\Documents\GitHub\purecore\landing\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (C:\Users\happy\Documents\GitHub\purecore\landing\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
Vite Error, /node_modules/.vite/deps/vue-frappe-chart.js?v=232d0f16 optimized info should be defined
```

my component:
```vue
<template>
    <v-frappe-chart />
</template>
<script>
import { VFrappeChart } from "vue-frappe-chart"
export default {
    components: {
        VFrappeChart,
    },
}
</script>
```

**Comment by carterbourette** [comment]
Hi, thanks for reporting! This should now be resolved in latest.
